name: Build / Test

on:
  push:
    branches:
      - main
  workflow_dispatch:  
  
jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up node
        uses: actions/setup-node@v4
      
      - name: Install Lib
        run: npm ci
      
      - name: Test
        run: npm run test
